name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: get current time
      run: export Tag=$(data +%s)
    - name: Get time
      run: echo $Tag
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag myjupyter:${Tag}
    - name: Run docker container
      run: docker run -d -p 80:80 --name quick-jupyter myjupyter:${Tag}
